name: status_cubit
description: Extension package providing further options above the popular Cubit class from well known BLoC package fluter_bloc
version: 1.1.0
repository: https://github.com/Kerrely/status_cubit
homepage: https://github.com/Kerrely/status_cubit

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  bloc_presentation: ^1.1.0
  flutter:
    sdk: flutter
  meta: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.7
  flutter_test:
    sdk: flutter
